### PR TITLE
Make configuration for each shell a separate process

### PR DESCRIPTION
**Pull request by Townk**
This commit splits the initialization based on the shells that the plugin supports.

### CODE REVIEW

**Comment by RobertDeRose** [comment]
Hey @Townk thanks for the PR, I will take a look at it. It looks very specific for ZPlug, which I have not tried yet.  I personally still use oh-my-zsh and this works perfectly for both that and bash as is.  

I like the update to the readme and the inclusion of a section for ZPlug is cool, but I wonder if it should include also how to use for things like antigen or oh-my-zsh?

I'll checkout your branch and make sure it works with my current setup and try out ZPlug before I accept or make comments.

**Comment by Townk** [comment]
Hi Robert, thanks for the feedback! The reason it has only ZPlug is because is what I used. I never used other plugin manager, but I believe most of them works in the same way, which means that there will be no changes on the code itself, only documentation.

I agree, the repo should have instructions and support to as many ways to install as possible. Maybe you could start with instructions on the oh-my-zsh?

Another reason for me to split the configuration in two was a bug I had (and I believe one or two other forks of your repo also faced the same thing). To see the problem do this:

Go to the settings of your terminal app (really doesn’t mater which app) and configure it to open a new tab on the same directory as the previous one.
Then, go to a directory with a .venv in it. It will happily activate it;
Now open a new tab to force ZSH to open in the same directory you were before.

What you will see, is that the environment is activated, but the prompt is not changed, and if you exit that directory, then your prompt will be broken.

I made a comment about this error, and explain why it happens with ZPlug, but this might also happen with other setups as well.

If you want me to do any change in the PR, please let me know!

**Comment by RobertDeRose** [comment]
@Townk My current biggest issue is that this loses all the blame.  Every line is now contributed to you.  I'm not an egotistical man, but I think the way you did it simply resulted in the loss of all the blame history.  I think we can make your changes and also keep the history if we tackle this a different way.  Also is there a ZPLUG environment variable set that we can look for to only load your change if it is detected.

Personally, I love this plugin, but I forked it off someone else and only originally made changes to support Mac and the adding and removing of PYTHONPATH because I worked with multi-repo projects all the time and I needed that.  Perhaps it time to make that configurable via an environment variable, because I find this plug is too slow.  I also want to think of a faster way to detect a virtualenv.

I'll have to put this all on hold though for the time being as I don't have the cycles while I am currently starting a new job and moving into a new house ATM.  

Hope you're OK with this PR not getting merged right away, but like I said, I'd like to see it done in a way that doesn't lose all the history and if possible to only load you prompt hack if ZPLUG is detected or possibly via an Environment variable you have to set in your `zshrc`

**Comment by Townk** [comment]
No worries at all. I'm doing a lot of refactor in my personal environment and I might have to tackle some of the things you just mentioned as well.

If I come up with a different approach, I will update the PR.

**Comment by Townk** [comment]
Hey, after a bunch of tests I could confirm that the problems I faced are exclusive to ZPlug. I'm closing this PR because I believe ZPlug maintainer should make his plugin manager works like all others.

**Comment by RobertDeRose** [comment]
@Townk OK, sounds good!  To be honest, I've never heard of ZPlug before this PR, but after reading up on it, it seems like it's the slowest manger out there. Have you tried ZPlugin, apparently it's everything ZPlug is, just better in all the ways.

**Comment by Townk** [comment]
ZPlugin is the one I'm migrating now. :)

**Pull request closed without merging**
